// <autogenerated>
// This code was generated by a tool. Any changes made manually will be lost
// the next time this code is regenerated.
// </autogenerated>

namespace Ethica.Measurements.Lengths
{
    /// <summary>
    /// Interface to assist with unboxing various representations of Length 
    /// </summary>
    interface ILength 
    {
    	/// <summary>
    	/// Gets the Length value
    	/// </summary>
    	Length Length {get;}
    }

}
