// <autogenerated>
// This code was generated by a tool. Any changes made manually will be lost
// the next time this code is regenerated.
// </autogenerated>

namespace Ethica.Measurements.Lengths
{
using System;
    
    /// <summary>
    /// Extends formatting and parsing abilities to Length measurements.
    /// </summary>
    public interface ILengthFormatProvider : ICustomFormatter
    {
        /// <summary>
        /// Attempts to convert a string to any suitable unit of measure
        /// </summary>
        /// <param name="value"></param>
        /// <param name="length"></param>
        /// <returns></returns>
        bool TryParse(string value, out Length length);
    
        /// <summary>
        /// Attempts to convert a string to a specific unit of measure
        /// </summary>
        /// <param name="value"></param>
        /// <param name="unitOfMeasure"></param>
        /// <param name="length"></param>
        /// <returns></returns>
        bool TryParse(string value, LengthUnit unitOfMeasure, out Length length);
    }

}
