// <autogenerated>
// This code was generated by a tool. Any changes made manually will be lost
// the next time this code is regenerated.
// </autogenerated>

namespace Ethica.Measurements.Lengths
{
    using System;
    using System.Globalization;
    using System.Resources;
    using System.Threading;
    using System.Collections.Concurrent;
    using System.Text;
    using System.Text.RegularExpressions;
    
    public partial class LengthFormatProvider : MeasurementFormatProvider<Length, LengthUnit>, 
    	ILengthFormatProvider
    {
        #region Fields
    
        private static readonly ConcurrentDictionary<string, LengthFormatProvider> CultureProviders =
            new ConcurrentDictionary<string, LengthFormatProvider>();
    
        #endregion
    
        public LengthFormatProvider(CultureInfo culture)
            : base(culture)
        {
        }
    
    	public LengthFormatProvider() : base()
        {
        }
    
    
        /// <summary>
        /// Gets the LengthFormatProvider object associated with the specified IFormatProvider object. 
        /// </summary>
        /// <param name="formatProvider"></param>
        /// <returns></returns>
        public static ILengthFormatProvider GetInstance(IFormatProvider formatProvider)
        {
            if (formatProvider == null)
                return Current;
    
            return (ILengthFormatProvider)formatProvider.GetFormat(typeof(ILengthFormatProvider))
                    ?? (ILengthFormatProvider)formatProvider.GetFormat(typeof(LengthFormatProvider))
                    ?? Current;
        }
    
        public static LengthFormatProvider ForCulture(CultureInfo culture)
        {
            if (culture == null) throw new ArgumentNullException("culture");
    
            return CultureProviders.GetOrAdd(culture.NativeName,
                                                name => new LengthFormatProvider(culture));
        }
    
    
        public static LengthFormatProvider Current
        {
            get { return ForCulture(Thread.CurrentThread.CurrentUICulture); }
        }
    
        protected override ResourceManager ResourceManager
        {
            get { return LengthResources.ResourceManager; }
        }
    
        protected override Length Factory(decimal value, LengthUnit unitOfMeasure)
        {
            return new Length(value, unitOfMeasure);
        }
    
        public string Format(string format, object arg, IFormatProvider formatProvider)
        {
            var asILength = arg as ILength;
            if (asILength == null)
                throw new ArgumentException("Invalid Argument","arg");
    
            Length length = asILength.Length;
    
            if (!string.IsNullOrEmpty(format))
            {
    			string unitName = length.UnitOfMeasure.ToString();
                
    			switch (format)
                {
                    case "g":
                        format = ResourceManager.GetString(unitName + "ShortFormat", Culture);
    					return string.Format(formatProvider, format, length);
    
                    case "G":
                        format = ResourceManager.GetString(unitName + "LongFormat", Culture);
    					return string.Format(formatProvider, format, length);
    
                    case "u":
                    case "uom":
                        return ResourceManager.GetString(unitName + "Short", Culture);
    
                    case "U":
                    case "UOM":
                        return ResourceManager.GetString(unitName + 
    					(length.Value == 1 ? "Single" : "Plural"), Culture);
                }
    
    
                string customResult = null;
    			CustomFormat(format, length, formatProvider, ref customResult);
                if (customResult != null)
                     return customResult;
    
                if (format.StartsWith("As", StringComparison.Ordinal))
                {
                    format = format.Substring(2);
                    LengthUnit unit;
                    if (Enum.TryParse(format, false, out unit))
                        return length.ConvertTo(unit).ToString("g", formatProvider);
                }
            }
            return length.Value.ToString(format, formatProvider);
        }
    
    
    	partial void CustomFormat(string format, Length length, IFormatProvider formatProvider, ref string result);
    
    }

}
