// <autogenerated>
// This code was generated by a tool. Any changes made manually will be lost
// the next time this code is regenerated.
// </autogenerated>

namespace Ethica.Measurements.Lengths
{
    /// <summary>
    /// Describes the known units of measurement for Lengths
    /// </summary>
    public enum LengthUnit
    {
    	Meters,
    	Centimeters,
    	Millimeters,
    	Nanometers,
    	Kilometers,
    	Inches,
    	Feet,
    	Yards,
    	Miles
    }

}
