//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ethica.Measurements.Lengths {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LengthResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LengthResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ethica.Measurements.Lengths.LengthResources", typeof(LengthResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {0:U}.
        /// </summary>
        internal static string CentimetersLongFormat {
            get {
                return ResourceManager.GetString("CentimetersLongFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to centimeters.
        /// </summary>
        internal static string CentimetersPlural {
            get {
                return ResourceManager.GetString("CentimetersPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (^(?&lt;Value&gt;(\d|\,)+(\.\d+)?)(?:\s?(cm|centimet(er|re))s?)\s*$).
        /// </summary>
        internal static string CentimetersRegex {
            get {
                return ResourceManager.GetString("CentimetersRegex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cm.
        /// </summary>
        internal static string CentimetersShort {
            get {
                return ResourceManager.GetString("CentimetersShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}{0:u}.
        /// </summary>
        internal static string CentimetersShortFormat {
            get {
                return ResourceManager.GetString("CentimetersShortFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to centimeter.
        /// </summary>
        internal static string CentimetersSingle {
            get {
                return ResourceManager.GetString("CentimetersSingle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (^(?&lt;Value&gt;(\d|\,)+)(?:\s?(?:&apos;|([fF](oo|ee)?t)))\s?(?&lt;Inches&gt;(\d|\.)+)(?:\s?(\&quot;|in(ch(es)?)?))\s*$).
        /// </summary>
        internal static string FeetAndInchesRegex {
            get {
                return ResourceManager.GetString("FeetAndInchesRegex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {0:U}.
        /// </summary>
        internal static string FeetLongFormat {
            get {
                return ResourceManager.GetString("FeetLongFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to feet.
        /// </summary>
        internal static string FeetPlural {
            get {
                return ResourceManager.GetString("FeetPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (^(?&lt;Value&gt;(\d|\.|\,)+)(?:\s?(?:&apos;|([fF](oo|ee)?t)))\s*$).
        /// </summary>
        internal static string FeetRegex {
            get {
                return ResourceManager.GetString("FeetRegex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;.
        /// </summary>
        internal static string FeetShort {
            get {
                return ResourceManager.GetString("FeetShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}{0:u}.
        /// </summary>
        internal static string FeetShortFormat {
            get {
                return ResourceManager.GetString("FeetShortFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to foot.
        /// </summary>
        internal static string FeetSingle {
            get {
                return ResourceManager.GetString("FeetSingle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {0:U}.
        /// </summary>
        internal static string InchesLongFormat {
            get {
                return ResourceManager.GetString("InchesLongFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to inches.
        /// </summary>
        internal static string InchesPlural {
            get {
                return ResourceManager.GetString("InchesPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (^(?&lt;Value&gt;(\d|\.|\,)+)(?:\s?(\&quot;|in(ch(es)?)?))\s*$).
        /// </summary>
        internal static string InchesRegex {
            get {
                return ResourceManager.GetString("InchesRegex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;.
        /// </summary>
        internal static string InchesShort {
            get {
                return ResourceManager.GetString("InchesShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}{0:u}.
        /// </summary>
        internal static string InchesShortFormat {
            get {
                return ResourceManager.GetString("InchesShortFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to inch.
        /// </summary>
        internal static string InchesSingle {
            get {
                return ResourceManager.GetString("InchesSingle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {0:U}.
        /// </summary>
        internal static string KilometersLongFormat {
            get {
                return ResourceManager.GetString("KilometersLongFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kilometers.
        /// </summary>
        internal static string KilometersPlural {
            get {
                return ResourceManager.GetString("KilometersPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (^(?&lt;Value&gt;(\d|\,)+(\.\d+)?)(?:\s?([kK]m|[Kk]ilomet(er|re))s?)\s*$).
        /// </summary>
        internal static string KilometersRegex {
            get {
                return ResourceManager.GetString("KilometersRegex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Km.
        /// </summary>
        internal static string KilometersShort {
            get {
                return ResourceManager.GetString("KilometersShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}{0:u}.
        /// </summary>
        internal static string KilometersShortFormat {
            get {
                return ResourceManager.GetString("KilometersShortFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kilometer.
        /// </summary>
        internal static string KilometersSingle {
            get {
                return ResourceManager.GetString("KilometersSingle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {0:U}.
        /// </summary>
        internal static string MetersLongFormat {
            get {
                return ResourceManager.GetString("MetersLongFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to meters.
        /// </summary>
        internal static string MetersPlural {
            get {
                return ResourceManager.GetString("MetersPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (^(?&lt;Value&gt;(\d|\,)+(\.\d+)?)(?:\s?(m|met(er|re))s?)\s*$).
        /// </summary>
        internal static string MetersRegex {
            get {
                return ResourceManager.GetString("MetersRegex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to m.
        /// </summary>
        internal static string MetersShort {
            get {
                return ResourceManager.GetString("MetersShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}{0:u}.
        /// </summary>
        internal static string MetersShortFormat {
            get {
                return ResourceManager.GetString("MetersShortFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to meter.
        /// </summary>
        internal static string MetersSingle {
            get {
                return ResourceManager.GetString("MetersSingle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {0:U}.
        /// </summary>
        internal static string MilesLongFormat {
            get {
                return ResourceManager.GetString("MilesLongFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to miles.
        /// </summary>
        internal static string MilesPlural {
            get {
                return ResourceManager.GetString("MilesPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (^(?&lt;Value&gt;(\d|\,)+(\.\d+)?)(?:\s?(mile)s?)\s*$).
        /// </summary>
        internal static string MilesRegex {
            get {
                return ResourceManager.GetString("MilesRegex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to miles.
        /// </summary>
        internal static string MilesShort {
            get {
                return ResourceManager.GetString("MilesShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}{0:u}.
        /// </summary>
        internal static string MilesShortFormat {
            get {
                return ResourceManager.GetString("MilesShortFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mile.
        /// </summary>
        internal static string MilesSingle {
            get {
                return ResourceManager.GetString("MilesSingle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {0:U}.
        /// </summary>
        internal static string MillimetersLongFormat {
            get {
                return ResourceManager.GetString("MillimetersLongFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to millimeters.
        /// </summary>
        internal static string MillimetersPlural {
            get {
                return ResourceManager.GetString("MillimetersPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (^(?&lt;Value&gt;(\d|\,)+(\.\d+)?)(?:\s?(mm|millimet(er|re))s?)\s*$).
        /// </summary>
        internal static string MillimetersRegex {
            get {
                return ResourceManager.GetString("MillimetersRegex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mm.
        /// </summary>
        internal static string MillimetersShort {
            get {
                return ResourceManager.GetString("MillimetersShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}{0:u}.
        /// </summary>
        internal static string MillimetersShortFormat {
            get {
                return ResourceManager.GetString("MillimetersShortFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to millimeter.
        /// </summary>
        internal static string MillimetersSingle {
            get {
                return ResourceManager.GetString("MillimetersSingle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {0:U}.
        /// </summary>
        internal static string NanometersLongFormat {
            get {
                return ResourceManager.GetString("NanometersLongFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nanometers.
        /// </summary>
        internal static string NanometersPlural {
            get {
                return ResourceManager.GetString("NanometersPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (^(?&lt;Value&gt;(\d|\,)+(\.\d+)?)(?:\s?(nm|nanomet(er|re))s?)\s*$).
        /// </summary>
        internal static string NanometersRegex {
            get {
                return ResourceManager.GetString("NanometersRegex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nm.
        /// </summary>
        internal static string NanometersShort {
            get {
                return ResourceManager.GetString("NanometersShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}{0:u}.
        /// </summary>
        internal static string NanometersShortFormat {
            get {
                return ResourceManager.GetString("NanometersShortFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nanometer.
        /// </summary>
        internal static string NanometersSingle {
            get {
                return ResourceManager.GetString("NanometersSingle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {0:U}.
        /// </summary>
        internal static string YardsLongFormat {
            get {
                return ResourceManager.GetString("YardsLongFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yards.
        /// </summary>
        internal static string YardsPlural {
            get {
                return ResourceManager.GetString("YardsPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (^(?&lt;Value&gt;(\d|\,)+(\.\d+)?)(?:\s?(y(ard|d)?)s?)\s*$).
        /// </summary>
        internal static string YardsRegex {
            get {
                return ResourceManager.GetString("YardsRegex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yd.
        /// </summary>
        internal static string YardsShort {
            get {
                return ResourceManager.GetString("YardsShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}{0:u}.
        /// </summary>
        internal static string YardsShortFormat {
            get {
                return ResourceManager.GetString("YardsShortFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yard.
        /// </summary>
        internal static string YardsSingle {
            get {
                return ResourceManager.GetString("YardsSingle", resourceCulture);
            }
        }
    }
}
