// <autogenerated>
// This code was generated by a tool. Any changes made manually will be lost
// the next time this code is regenerated.
// </autogenerated>

namespace Ethica.Measurements.Lengths
{
    using System;
    using System.ComponentModel;
    using System.Globalization;
    using Ethica.Measurements.Properties;
    
    	public partial class MillimetersConverter : LengthBaseConverter
    	{
    		protected override object ConvertFrom(Length length)
    		{
    			return (Millimeters)length;
    		}     
    	}

}
