// <autogenerated>
// This code was generated by a tool. Any changes made manually will be lost
// the next time this code is regenerated.
// </autogenerated>

namespace Ethica.Measurements.Mass
{
using System;
    
    /// <summary>
    /// Extends formatting and parsing abilities to Mass measurements.
    /// </summary>
    public interface IMassFormatProvider : ICustomFormatter
    {
        /// <summary>
        /// Attempts to convert a string to any suitable unit of measure
        /// </summary>
        /// <param name="value"></param>
        /// <param name="mass"></param>
        /// <returns></returns>
        bool TryParse(string value, out Mass mass);
    
        /// <summary>
        /// Attempts to convert a string to a specific unit of measure
        /// </summary>
        /// <param name="value"></param>
        /// <param name="unitOfMeasure"></param>
        /// <param name="mass"></param>
        /// <returns></returns>
        bool TryParse(string value, MassUnit unitOfMeasure, out Mass mass);
    }

}
