// <autogenerated>
// This code was generated by a tool. Any changes made manually will be lost
// the next time this code is regenerated.
// </autogenerated>

namespace Ethica.Measurements.Mass
{
    /// <summary>
    /// Interface to assist with unboxing various representations of Mass 
    /// </summary>
    interface IMass 
    {
    	/// <summary>
    	/// Gets the Mass value
    	/// </summary>
    	Mass Mass {get;}
    }

}
