// <autogenerated>
// This code was generated by a tool. Any changes made manually will be lost
// the next time this code is regenerated.
// </autogenerated>

namespace Ethica.Measurements.Mass
{
    using System;
    using System.ComponentModel;
    using System.Globalization;
    using Ethica.Measurements.Properties;
    
    	public partial class KilogramsConverter : MassBaseConverter
    	{
    		protected override object ConvertFrom(Mass mass)
    		{
    			return (Kilograms)mass;
    		}     
    	}

}
