// <autogenerated>
// This code was generated by a tool. Any changes made manually will be lost
// the next time this code is regenerated.
// </autogenerated>

namespace Ethica.Measurements.Mass
{
    /// <summary>
    /// Describes the known units of measurement for Mass
    /// </summary>
    public enum MassUnit
    {
    	Grams,
    	Kilograms,
    	Ounces,
    	Milligrams,
    	Pounds
    }

}
