//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ethica.Measurements.Mass {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MassResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MassResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ethica.Measurements.Mass.MassResources", typeof(MassResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {0:U}.
        /// </summary>
        internal static string GramsLongFormat {
            get {
                return ResourceManager.GetString("GramsLongFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to grams.
        /// </summary>
        internal static string GramsPlural {
            get {
                return ResourceManager.GetString("GramsPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (^(?&lt;Value&gt;(\d|\,)+(\.\d+)?)(?:\s?g(ram)?s?)\s*$).
        /// </summary>
        internal static string GramsRegex {
            get {
                return ResourceManager.GetString("GramsRegex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to g.
        /// </summary>
        internal static string GramsShort {
            get {
                return ResourceManager.GetString("GramsShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}{0:u}.
        /// </summary>
        internal static string GramsShortFormat {
            get {
                return ResourceManager.GetString("GramsShortFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gram.
        /// </summary>
        internal static string GramsSingle {
            get {
                return ResourceManager.GetString("GramsSingle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {0:U}.
        /// </summary>
        internal static string KilogramsLongFormat {
            get {
                return ResourceManager.GetString("KilogramsLongFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kilograms.
        /// </summary>
        internal static string KilogramsPlural {
            get {
                return ResourceManager.GetString("KilogramsPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (^(?&lt;Value&gt;(\d|\,)+(\.\d+)?)(?:\s?[Kk](g|ilo(gram)?s?)\s*$).
        /// </summary>
        internal static string KilogramsRegex {
            get {
                return ResourceManager.GetString("KilogramsRegex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kg.
        /// </summary>
        internal static string KilogramsShort {
            get {
                return ResourceManager.GetString("KilogramsShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}{0:u}.
        /// </summary>
        internal static string KilogramsShortFormat {
            get {
                return ResourceManager.GetString("KilogramsShortFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kilogram.
        /// </summary>
        internal static string KilogramsSingle {
            get {
                return ResourceManager.GetString("KilogramsSingle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {0:U}.
        /// </summary>
        internal static string MilligramsLongFormat {
            get {
                return ResourceManager.GetString("MilligramsLongFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to milligrams.
        /// </summary>
        internal static string MilligramsPlural {
            get {
                return ResourceManager.GetString("MilligramsPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (^(?&lt;Value&gt;(\d|\,)+(\.\d+)?)(?:\s?(mg|milligrams?))\s*$).
        /// </summary>
        internal static string MilligramsRegex {
            get {
                return ResourceManager.GetString("MilligramsRegex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mg.
        /// </summary>
        internal static string MilligramsShort {
            get {
                return ResourceManager.GetString("MilligramsShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}{0:u}.
        /// </summary>
        internal static string MilligramsShortFormat {
            get {
                return ResourceManager.GetString("MilligramsShortFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to milligram.
        /// </summary>
        internal static string MilligramsSingle {
            get {
                return ResourceManager.GetString("MilligramsSingle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {0:U}.
        /// </summary>
        internal static string OuncesLongFormat {
            get {
                return ResourceManager.GetString("OuncesLongFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ounces.
        /// </summary>
        internal static string OuncesPlural {
            get {
                return ResourceManager.GetString("OuncesPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (^(?&lt;Value&gt;(\d|\,)+(\.\d+)?)(?:\s?[Oo](z|unces?)?)\s*$).
        /// </summary>
        internal static string OuncesRegex {
            get {
                return ResourceManager.GetString("OuncesRegex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to oz.
        /// </summary>
        internal static string OuncesShort {
            get {
                return ResourceManager.GetString("OuncesShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}{0:u}.
        /// </summary>
        internal static string OuncesShortFormat {
            get {
                return ResourceManager.GetString("OuncesShortFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ounce.
        /// </summary>
        internal static string OuncesSingle {
            get {
                return ResourceManager.GetString("OuncesSingle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {0:U}.
        /// </summary>
        internal static string PoundsLongFormat {
            get {
                return ResourceManager.GetString("PoundsLongFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pounds.
        /// </summary>
        internal static string PoundsPlural {
            get {
                return ResourceManager.GetString("PoundsPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (^(?&lt;Value&gt;(\d|\,)+(\.\d+)?)(?:\s?(lbs|[Pp]ounds?))\s*$).
        /// </summary>
        internal static string PoundsRegex {
            get {
                return ResourceManager.GetString("PoundsRegex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lbs.
        /// </summary>
        internal static string PoundsShort {
            get {
                return ResourceManager.GetString("PoundsShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}{0:u}.
        /// </summary>
        internal static string PoundsShortFormat {
            get {
                return ResourceManager.GetString("PoundsShortFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pound.
        /// </summary>
        internal static string PoundsSingle {
            get {
                return ResourceManager.GetString("PoundsSingle", resourceCulture);
            }
        }
    }
}
