// <autogenerated>
// This code was generated by a tool. Any changes made manually will be lost
// the next time this code is regenerated.
// </autogenerated>

namespace Ethica.Measurements.Mass
{
using System;
    using System.ComponentModel;
    
    [TypeConverter(typeof(OuncesConverter))]
    public partial struct Ounces :
    	IMass,
    	IFormattable,
    	IEquatable<Mass>,
        IEquatable<Grams>,
        IEquatable<Kilograms>,
        IEquatable<Ounces>,
        IEquatable<Milligrams>,
        IEquatable<Pounds>,
        IComparable<Grams>,
        IComparable<Kilograms>,
        IComparable<Ounces>,
        IComparable<Milligrams>,
        IComparable<Pounds>
    {
    	public static readonly decimal GramsPerUnit = 28.349523125M;
    	public static readonly decimal UnitsPerGrams = 0.0352739619495804129156758082M;
    
    	#region Fields
    
        /// <summary>
        /// The value of the Mass represented by RelativeUnits
        /// </summary>
        readonly decimal _value;
    
        #endregion
    
    	#region Properties
    
        /// <summary>
        /// The value of the Mass represented by RelativeUnits
        /// </summary>
        public decimal Value { get { return _value; } }
        
    	#endregion
    
    	public Ounces(decimal value)
    	{
    		_value = value;
    	}
    
    	#region Equality
    
        /// <summary>
        /// Equates whether this value is the same as another value.
        /// </summary>
        /// <param name="obj">The value to compare to</param>
        /// <returns>True if both values are equal</returns>
        public override bool Equals(object obj)
        {
            var other = obj as IMass;
            if (other != null)
                return Equals(other.Mass);
    
            return false;
        }
    
        /// <summary>
        /// Equates whether this value is the same as another value.
        /// </summary>
        /// <param name="other">The distance to compare to</param>
        /// <returns>True if both values are equal</returns>
    	public bool Equals(Mass other)
        {
            return other.ConvertTo(MassUnit.Ounces).Value == this.Value;
        }
    
    	/// <summary>
        /// Equates whether this value is the same as another value.
        /// </summary>
        /// <param name="other">The distance to compare to</param>
        /// <returns>True if both values are equal</returns>
    	public bool Equals(Ounces other)
        {
            return Value.Equals(other.Value);
        }
    
    	public bool Equals(Grams other)
        {
            return Equals(((Ounces)other));
        }	
    								
    	public bool Equals(Kilograms other)
        {
            return Equals(((Ounces)other));
        }	
    								
    	public bool Equals(Milligrams other)
        {
            return Equals(((Ounces)other));
        }	
    								
    	public bool Equals(Pounds other)
        {
            return Equals(((Ounces)other));
        }	
    								
    	public static bool operator == (Ounces arg1, Ounces arg2)
    	{
    		return arg1.Equals(arg2);
    	}
    
    	public static bool operator != (Ounces arg1, Ounces arg2)
    	{
    		return !arg1.Equals(arg2);
    	}
    
        public override int GetHashCode()
        {
            return Value.GetHashCode();
        }
    
    	#endregion Equality
    
    	#region Comparable
    		
        public static bool operator <(Ounces arg1, Ounces arg2)
        {
            return arg1.CompareTo(arg2) == -1;
        }
    
        public static bool operator >(Ounces arg1, Ounces arg2)
        {
            return arg1.CompareTo(arg2) == 1;
        }
    
    	public int CompareTo(Mass other)
        {
            return Value.CompareTo(other.ConvertTo(MassUnit.Ounces).Value);
        }
    
    	public int CompareTo(Ounces other)
        {
            return Value.CompareTo(other.Value);
        }
    
    	public int CompareTo(Grams other)
        {
            return CompareTo((Ounces)other);
        }	
    								
    	public int CompareTo(Kilograms other)
        {
            return CompareTo((Ounces)other);
        }	
    								
    	public int CompareTo(Milligrams other)
        {
            return CompareTo((Ounces)other);
        }	
    								
    	public int CompareTo(Pounds other)
        {
            return CompareTo((Ounces)other);
        }	
    								
    	#endregion Comparable
    
    	#region Implicit Type Casting
    
    	public static implicit operator Ounces (Mass obj)
        {
    		return new Ounces(obj.ConvertTo(MassUnit.Ounces).Value);
        }	
    
    	public static implicit operator Mass(Ounces obj)
        {
    		return new Mass(obj.Value, MassUnit.Ounces);
        }	
    
    	public static implicit operator Ounces(Grams obj)
        {
    		return new Ounces(obj.Value * Grams.GramsPerUnit * Ounces.UnitsPerGrams);
        }	
    			
    	public static implicit operator Ounces(Kilograms obj)
        {
    		return new Ounces(obj.Value * Kilograms.GramsPerUnit * Ounces.UnitsPerGrams);
        }	
    			
    	public static implicit operator Ounces(Milligrams obj)
        {
    		return new Ounces(obj.Value * Milligrams.GramsPerUnit * Ounces.UnitsPerGrams);
        }	
    			
    	public static implicit operator Ounces(Pounds obj)
        {
    		return new Ounces(obj.Value * Pounds.GramsPerUnit * Ounces.UnitsPerGrams);
        }	
    			
    	#endregion
    
    	#region ToString
    
    	public string ToString(string format, IFormatProvider formatProvider)
        {
    		var provider = MassFormatProvider.GetInstance(formatProvider);
    		return provider.Format(format, this, formatProvider);
        }
    
    	public string ToString(string format)
        {
    		return ToString(format, null);
        }
    
    	public override string ToString()
        {
    		return ToString("g", null);
        }
    
    	#endregion
    
    	#region TryParse
    
    	/// <summary>
        /// Attempts to parse a string into a Ounces value 
        /// </summary>
    	/// <param name="formatProvider">The format provider to use for parsing</param>
    	/// <param name="value">the string to parse</param>
        /// <param name="result">the parsed value</param>
        /// <returns>true, if succesful</returns>
    	public static bool TryParse(string value, IFormatProvider formatProvider, out Ounces result)
    	{
    		var provider =  MassFormatProvider.GetInstance(formatProvider);
    			
    		Mass distanceResult;
    		if(provider.TryParse(value, MassUnit.Ounces, out distanceResult))
    		{
    			result = distanceResult;
    			return true;				
    		}
    
    		result = default(Ounces);
    		return false;
    	}
    
    	/// <summary>
        /// Attempts to parse a string into a Ounces value 
        /// </summary>
        /// <param name="value">the string to parse</param>
        /// <param name="result">the parsed value</param>
        /// <returns>true, if succesful</returns>
    	public static bool TryParse(string value, out Ounces result)
    	{
    		return TryParse(value, null, out result);
    	}
    
    	#endregion
    
        #region IMass Members
    
    	/// <summary>
        /// Gets this value as an unboxable property
        /// </summary>
        Mass IMass.Mass
        {
            get { return this; }
        }
    
        #endregion
    }
}
