// <autogenerated>
// This code was generated by a tool. Any changes made manually will be lost
// the next time this code is regenerated.
// </autogenerated>

namespace Ethica.Measurements.Volumes
{
using System;
    
    /// <summary>
    /// Extends formatting and parsing abilities to Volume measurements.
    /// </summary>
    public interface IVolumeFormatProvider : ICustomFormatter
    {
        /// <summary>
        /// Attempts to convert a string to any suitable unit of measure
        /// </summary>
        /// <param name="value"></param>
        /// <param name="volume"></param>
        /// <returns></returns>
        bool TryParse(string value, out Volume volume);
    
        /// <summary>
        /// Attempts to convert a string to a specific unit of measure
        /// </summary>
        /// <param name="value"></param>
        /// <param name="unitOfMeasure"></param>
        /// <param name="volume"></param>
        /// <returns></returns>
        bool TryParse(string value, VolumeUnit unitOfMeasure, out Volume volume);
    }

}
