// <autogenerated>
// This code was generated by a tool. Any changes made manually will be lost
// the next time this code is regenerated.
// </autogenerated>

namespace Ethica.Measurements.Volumes
{
    /// <summary>
    /// Interface to assist with unboxing various representations of Volume 
    /// </summary>
    interface IVolume 
    {
    	/// <summary>
    	/// Gets the Volume value
    	/// </summary>
    	Volume Volume {get;}
    }

}
