//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ethica.Measurements.Volumes {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class VolumeResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal VolumeResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ethica.Measurements.Volumes.VolumeResources", typeof(VolumeResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {0:U}.
        /// </summary>
        internal static string CubicCentimetersLongFormat {
            get {
                return ResourceManager.GetString("CubicCentimetersLongFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cubic centimeters.
        /// </summary>
        internal static string CubicCentimetersPlural {
            get {
                return ResourceManager.GetString("CubicCentimetersPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (^(?&lt;Value&gt;(\d|\.|\,)+)(?:\s?([Dd]m(3|³)|(C|c)ubic\s(dm|cm|[Cc]entimeters?)))\s*$).
        /// </summary>
        internal static string CubicCentimetersRegex {
            get {
                return ResourceManager.GetString("CubicCentimetersRegex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dm³.
        /// </summary>
        internal static string CubicCentimetersShort {
            get {
                return ResourceManager.GetString("CubicCentimetersShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}{0:u}.
        /// </summary>
        internal static string CubicCentimetersShortFormat {
            get {
                return ResourceManager.GetString("CubicCentimetersShortFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cubic centimeter.
        /// </summary>
        internal static string CubicCentimetersSingle {
            get {
                return ResourceManager.GetString("CubicCentimetersSingle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {0:U}.
        /// </summary>
        internal static string CubicFeetLongFormat {
            get {
                return ResourceManager.GetString("CubicFeetLongFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cubic feet.
        /// </summary>
        internal static string CubicFeetPlural {
            get {
                return ResourceManager.GetString("CubicFeetPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (^(?&lt;Value&gt;(\d|\.|\,)+)(?:\s?([Ff]t(3|³)|(C|c)ubic\s[Ff](ee|oo)?t?))\s*$).
        /// </summary>
        internal static string CubicFeetRegex {
            get {
                return ResourceManager.GetString("CubicFeetRegex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ft³.
        /// </summary>
        internal static string CubicFeetShort {
            get {
                return ResourceManager.GetString("CubicFeetShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}{0:u}.
        /// </summary>
        internal static string CubicFeetShortFormat {
            get {
                return ResourceManager.GetString("CubicFeetShortFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cubic feet.
        /// </summary>
        internal static string CubicFeetSingle {
            get {
                return ResourceManager.GetString("CubicFeetSingle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {0:U}.
        /// </summary>
        internal static string CubicInchesLongFormat {
            get {
                return ResourceManager.GetString("CubicInchesLongFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cubic inches.
        /// </summary>
        internal static string CubicInchesPlural {
            get {
                return ResourceManager.GetString("CubicInchesPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (^(?&lt;Value&gt;(\d|\.|\,)+)(?:\s?(in(3|³)|(C|c)ubic\s[Ii]n(ch(es)?)?))\s*$).
        /// </summary>
        internal static string CubicInchesRegex {
            get {
                return ResourceManager.GetString("CubicInchesRegex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to in³.
        /// </summary>
        internal static string CubicInchesShort {
            get {
                return ResourceManager.GetString("CubicInchesShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}{0:u}.
        /// </summary>
        internal static string CubicInchesShortFormat {
            get {
                return ResourceManager.GetString("CubicInchesShortFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cubic inch.
        /// </summary>
        internal static string CubicInchesSingle {
            get {
                return ResourceManager.GetString("CubicInchesSingle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {0:U}.
        /// </summary>
        internal static string CubicMetersLongFormat {
            get {
                return ResourceManager.GetString("CubicMetersLongFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cubic meters.
        /// </summary>
        internal static string CubicMetersPlural {
            get {
                return ResourceManager.GetString("CubicMetersPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (^(?&lt;Value&gt;(\d|\.|\,)+)(?:\s?(m(3|³)|(C|c)ubic\s[Mm](eters?)?))\s*$).
        /// </summary>
        internal static string CubicMetersRegex {
            get {
                return ResourceManager.GetString("CubicMetersRegex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to m³.
        /// </summary>
        internal static string CubicMetersShort {
            get {
                return ResourceManager.GetString("CubicMetersShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}{0:u}.
        /// </summary>
        internal static string CubicMetersShortFormat {
            get {
                return ResourceManager.GetString("CubicMetersShortFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cubic meter.
        /// </summary>
        internal static string CubicMetersSingle {
            get {
                return ResourceManager.GetString("CubicMetersSingle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {0:U}.
        /// </summary>
        internal static string CubicYardsLongFormat {
            get {
                return ResourceManager.GetString("CubicYardsLongFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cubic yards.
        /// </summary>
        internal static string CubicYardsPlural {
            get {
                return ResourceManager.GetString("CubicYardsPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (^(?&lt;Value&gt;(\d|\.|\,)+)(?:\s?(yd(3|³)|(C|c)ubic\s[Yy](ar)?ds?))\s*$).
        /// </summary>
        internal static string CubicYardsRegex {
            get {
                return ResourceManager.GetString("CubicYardsRegex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yd³.
        /// </summary>
        internal static string CubicYardsShort {
            get {
                return ResourceManager.GetString("CubicYardsShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}{0:u}.
        /// </summary>
        internal static string CubicYardsShortFormat {
            get {
                return ResourceManager.GetString("CubicYardsShortFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cubic yard.
        /// </summary>
        internal static string CubicYardsSingle {
            get {
                return ResourceManager.GetString("CubicYardsSingle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {0:U}.
        /// </summary>
        internal static string FluidOuncesLongFormat {
            get {
                return ResourceManager.GetString("FluidOuncesLongFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fluid ounces.
        /// </summary>
        internal static string FluidOuncesPlural {
            get {
                return ResourceManager.GetString("FluidOuncesPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (^(?&lt;Value&gt;(\d|\.|\,)+)(?:\s?[Ff]l(uid\s|\s|\.)[Oo](z|unces?))\s * $).
        /// </summary>
        internal static string FluidOuncesRegex {
            get {
                return ResourceManager.GetString("FluidOuncesRegex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fl.oz.
        /// </summary>
        internal static string FluidOuncesShort {
            get {
                return ResourceManager.GetString("FluidOuncesShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {0:u}.
        /// </summary>
        internal static string FluidOuncesShortFormat {
            get {
                return ResourceManager.GetString("FluidOuncesShortFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fluid ounce.
        /// </summary>
        internal static string FluidOuncesSingle {
            get {
                return ResourceManager.GetString("FluidOuncesSingle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {0:U}.
        /// </summary>
        internal static string FluidOuncesUKLongFormat {
            get {
                return ResourceManager.GetString("FluidOuncesUKLongFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fluid ounces (UK).
        /// </summary>
        internal static string FluidOuncesUKPlural {
            get {
                return ResourceManager.GetString("FluidOuncesUKPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (^(?&lt;Value&gt;(\d|\.|\,)+)(?:\s?[Ff]l(uid\s|\s|\.)[Oo](z|unces?)\s?\((Uk|uk|UK)\))\s * $).
        /// </summary>
        internal static string FluidOuncesUKRegex {
            get {
                return ResourceManager.GetString("FluidOuncesUKRegex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fl.oz (UK).
        /// </summary>
        internal static string FluidOuncesUKShort {
            get {
                return ResourceManager.GetString("FluidOuncesUKShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {0:u}.
        /// </summary>
        internal static string FluidOuncesUKShortFormat {
            get {
                return ResourceManager.GetString("FluidOuncesUKShortFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fluid ounce (UK).
        /// </summary>
        internal static string FluidOuncesUKSingle {
            get {
                return ResourceManager.GetString("FluidOuncesUKSingle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {0:U}.
        /// </summary>
        internal static string GallonsLongFormat {
            get {
                return ResourceManager.GetString("GallonsLongFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gallons.
        /// </summary>
        internal static string GallonsPlural {
            get {
                return ResourceManager.GetString("GallonsPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (^(?&lt;Value&gt;(\d|\.|\,)+)(?:\s?[Gg]al(lons?)?)\s * $).
        /// </summary>
        internal static string GallonsRegex {
            get {
                return ResourceManager.GetString("GallonsRegex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gal.
        /// </summary>
        internal static string GallonsShort {
            get {
                return ResourceManager.GetString("GallonsShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}{0:u}.
        /// </summary>
        internal static string GallonsShortFormat {
            get {
                return ResourceManager.GetString("GallonsShortFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gallon.
        /// </summary>
        internal static string GallonsSingle {
            get {
                return ResourceManager.GetString("GallonsSingle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {0:U}.
        /// </summary>
        internal static string GallonsUKLongFormat {
            get {
                return ResourceManager.GetString("GallonsUKLongFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gallons (UK).
        /// </summary>
        internal static string GallonsUKPlural {
            get {
                return ResourceManager.GetString("GallonsUKPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (^(?&lt;Value&gt;(\d|\.|\,)+)(?:\s?[Gg]al(lons?)?\s?\((Uk|uk|UK)\))\s * $).
        /// </summary>
        internal static string GallonsUKRegex {
            get {
                return ResourceManager.GetString("GallonsUKRegex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gal (UK).
        /// </summary>
        internal static string GallonsUKShort {
            get {
                return ResourceManager.GetString("GallonsUKShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {0:u}.
        /// </summary>
        internal static string GallonsUKShortFormat {
            get {
                return ResourceManager.GetString("GallonsUKShortFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gallon (UK).
        /// </summary>
        internal static string GallonsUKSingle {
            get {
                return ResourceManager.GetString("GallonsUKSingle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {0:U}.
        /// </summary>
        internal static string LitersLongFormat {
            get {
                return ResourceManager.GetString("LitersLongFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to liters.
        /// </summary>
        internal static string LitersPlural {
            get {
                return ResourceManager.GetString("LitersPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (^(?&lt;Value&gt;(\d|\.|\,)+)(?:\s?[Ll](it(er|re)s?)?)\s * $).
        /// </summary>
        internal static string LitersRegex {
            get {
                return ResourceManager.GetString("LitersRegex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L.
        /// </summary>
        internal static string LitersShort {
            get {
                return ResourceManager.GetString("LitersShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}{0:u}.
        /// </summary>
        internal static string LitersShortFormat {
            get {
                return ResourceManager.GetString("LitersShortFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to liter.
        /// </summary>
        internal static string LitersSingle {
            get {
                return ResourceManager.GetString("LitersSingle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {0:U}.
        /// </summary>
        internal static string PintsLongFormat {
            get {
                return ResourceManager.GetString("PintsLongFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pints.
        /// </summary>
        internal static string PintsPlural {
            get {
                return ResourceManager.GetString("PintsPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (^(?&lt;Value&gt;(\d|\.|\,)+)(?:\s?[Pp](in)?ts?)\s * $).
        /// </summary>
        internal static string PintsRegex {
            get {
                return ResourceManager.GetString("PintsRegex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pt.
        /// </summary>
        internal static string PintsShort {
            get {
                return ResourceManager.GetString("PintsShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}{0:u}.
        /// </summary>
        internal static string PintsShortFormat {
            get {
                return ResourceManager.GetString("PintsShortFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pint.
        /// </summary>
        internal static string PintsSingle {
            get {
                return ResourceManager.GetString("PintsSingle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {0:U}.
        /// </summary>
        internal static string PintsUKLongFormat {
            get {
                return ResourceManager.GetString("PintsUKLongFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pints (UK).
        /// </summary>
        internal static string PintsUKPlural {
            get {
                return ResourceManager.GetString("PintsUKPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (^(?&lt;Value&gt;(\d|\.|\,)+)(?:\s?[Pp](in)?ts?\s?\((Uk|uk|UK)\))\s * $).
        /// </summary>
        internal static string PintsUKRegex {
            get {
                return ResourceManager.GetString("PintsUKRegex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pt (UK).
        /// </summary>
        internal static string PintsUKShort {
            get {
                return ResourceManager.GetString("PintsUKShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {0:u}.
        /// </summary>
        internal static string PintsUKShortFormat {
            get {
                return ResourceManager.GetString("PintsUKShortFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pint (UK).
        /// </summary>
        internal static string PintsUKSingle {
            get {
                return ResourceManager.GetString("PintsUKSingle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {0:U}.
        /// </summary>
        internal static string QuartsLongFormat {
            get {
                return ResourceManager.GetString("QuartsLongFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to quarts.
        /// </summary>
        internal static string QuartsPlural {
            get {
                return ResourceManager.GetString("QuartsPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (^(?&lt;Value&gt;(\d|\.|\,)+)(?:\s?[Qq](uar)?ts?)\s * $).
        /// </summary>
        internal static string QuartsRegex {
            get {
                return ResourceManager.GetString("QuartsRegex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to qt.
        /// </summary>
        internal static string QuartsShort {
            get {
                return ResourceManager.GetString("QuartsShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {0:u}.
        /// </summary>
        internal static string QuartsShortFormat {
            get {
                return ResourceManager.GetString("QuartsShortFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to quart.
        /// </summary>
        internal static string QuartsSingle {
            get {
                return ResourceManager.GetString("QuartsSingle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {0:U}.
        /// </summary>
        internal static string QuartsUKLongFormat {
            get {
                return ResourceManager.GetString("QuartsUKLongFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to quarts (UK).
        /// </summary>
        internal static string QuartsUKPlural {
            get {
                return ResourceManager.GetString("QuartsUKPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (^(?&lt;Value&gt;(\d|\.|\,)+)(?:\s?[Qq](uar)?ts?\s?\((Uk|uk|UK)\))\s * $).
        /// </summary>
        internal static string QuartsUKRegex {
            get {
                return ResourceManager.GetString("QuartsUKRegex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to qt (UK).
        /// </summary>
        internal static string QuartsUKShort {
            get {
                return ResourceManager.GetString("QuartsUKShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {0:u}.
        /// </summary>
        internal static string QuartsUKShortFormat {
            get {
                return ResourceManager.GetString("QuartsUKShortFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to quart (UK).
        /// </summary>
        internal static string QuartsUKSingle {
            get {
                return ResourceManager.GetString("QuartsUKSingle", resourceCulture);
            }
        }
    }
}
