// <autogenerated>
// This code was generated by a tool. Any changes made manually will be lost
// the next time this code is regenerated.
// </autogenerated>

namespace Ethica.Measurements.Volumes
{
    /// <summary>
    /// Describes the known units of measurement for Volumes
    /// </summary>
    public enum VolumeUnit
    {
    	Liters,
    	CubicMeters,
    	CubicCentimeters,
    	CubicFeet,
    	CubicInches,
    	CubicYards,
    	FluidOuncesUK,
    	FluidOunces,
    	PintsUK,
    	Pints,
    	QuartsUK,
    	Quarts,
    	GallonsUK,
    	Gallons
    }

}
